# Generated by Django 4.2 on 2023-07-09 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=255, verbose_name='примечания')),
                ('status', models.BooleanField(default=False)),
                ('energy', models.PositiveIntegerField(default=0, verbose_name='Energy')),
                ('type', models.CharField(choices=[('Text', 'Text'), ('Document', 'Document'), ('Link', 'Link')], max_length=10, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=1000)),
                ('result', models.CharField(max_length=5000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tools', models.ManyToManyField(related_name='results', to='core.tool')),
                ('users', models.ManyToManyField(related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Рузултаты',
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('users', models.ManyToManyField(related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
            },
        ),
    ]
