# Generated by Django 4.2 on 2023-07-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0004_remove_tariff_users_alter_products_description'),
        ('oauth', '0002_alter_user_is_active_alter_user_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tarrif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tariffs.tariff'),
        ),
    ]
