# Generated by Django 4.2 on 2023-07-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_user_tarrif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tarrif',
            new_name='tariff',
        ),
    ]
