# Generated by Django 4.2 on 2023-07-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='renew_date',
            field=models.DateTimeField(auto_now=True, verbose_name='renew_date'),
        ),
    ]
