# Generated by Django 4.2 on 2023-07-09 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('energy_copy', models.PositiveIntegerField(default=0, verbose_name='energy copy')),
                ('refil', models.PositiveIntegerField(default=0)),
                ('price_month', models.PositiveIntegerField(default=0)),
                ('price_year', models.PositiveIntegerField(default=0)),
                ('economie', models.PositiveIntegerField(default=0)),
                ('storage', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, verbose_name='Статус')),
                ('users', models.ManyToManyField(related_name='tariff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=5000, verbose_name='Описание')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, verbose_name='Статус')),
                ('tariffs', models.ManyToManyField(related_name='products', to='tariffs.tariff')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
