# Generated by Django 4.2 on 2023-07-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='storage',
            field=models.FloatField(default=0),
        ),
    ]
