# Generated by Django 4.2 on 2023-07-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_alter_tariff_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='tariffs',
        ),
        migrations.AddField(
            model_name='tariff',
            name='products',
            field=models.ManyToManyField(related_name='tariffs', to='tariffs.products'),
        ),
    ]
