# Generated by Django 4.2 on 2023-07-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0003_remove_products_tariffs_tariff_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='users',
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Описание'),
        ),
    ]
