# Generated by Django 4.2 on 2023-07-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0006_alter_payment_amount_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(default='dasds', max_length=500),
            preserve_default=False,
        ),
    ]
