# Generated by Django 4.2 on 2023-07-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0009_alter_payment_tariff_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='stripeCustomerId',
            field=models.CharField(default=2121, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='stripeSubscriptionId',
            field=models.CharField(default=21312, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
