# Generated by Django 4.2 on 2023-07-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0010_tariff_stripecustomerid_tariff_stripesubscriptionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='status',
            field=models.CharField(max_length=10, verbose_name='Статус'),
        ),
    ]
